# Nome do sistema
spring.application.name=api-tarifa-agua

# Conexao com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tarifa_agua_db
spring.datasource.username=postgres
spring.datasource.password=Senha@123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# SQL inicial (categorias)
spring.sql.init.mode=always

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Log SQL com valores
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jackson.serialization.indent-output=true